### ISSUE TITLE
Build failure against kernel 5.15.79

### ISSUE THREAD

**Issue by zenmetsu** [v-kiniv/noritake-gud-drm#1] opened 2022-11-27 19:13 UTC
Good day!

I am interested in using your framebuffer code for a project I am working on, however I ran into a compilation issue and I am not quite certain how to proceed.  Do I need to include something in my kernel?

```
make -j4
make -C "/lib/modules/5.15.79-v8+/build" M="/home/arrow/build/noritake-gud-drm" modules
make[1]: Entering directory '/usr/src/linux'
  CC [M]  /home/arrow/build/noritake-gud-drm/gud.o
/home/arrow/build/noritake-gud-drm/gud.c:657:17: error: ‘drm_gem_fb_simple_display_pipe_prepare_fb’ undeclared here (not in a function)
  657 |   .prepare_fb = drm_gem_fb_simple_display_pipe_prepare_fb,
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:289: /home/arrow/build/noritake-gud-drm/gud.o] Error 1
make[1]: *** [Makefile:1900: /home/arrow/build/noritake-gud-drm] Error 2
make[1]: Leaving directory '/usr/src/linux'
make: *** [Makefile:9: all] Error 2
```

**Comment by v-kiniv** [comment] 2022-11-27 19:35
Seems like it's caused by the latest changes in the kernel. I created PR with fix, I didn't tried it because I'm running 5.10 right now, so please check and let me know if it works for you.

https://github.com/v-kiniv/noritake-gud-drm/pull/2

**Comment by zenmetsu** [comment] 2022-11-27 19:47
That appears to have worked. Thanks.

**Comment by v-kiniv** [comment] 2022-11-27 19:51
Great, I'll close the issue then

**Closed as completed** 2022-11-27 19:51 UTC
